/**
 * 武将译名、前缀键
 */
export const characterTranslate = {
	群芳: "群芳",
	qunfang_sunshangxiang: "飘萍孙尚香",
	qunfang_sunshangxiang_prefix: "飘萍",
	qunfang_zhaoxiang: "飘萍赵襄",
	qunfang_zhaoxiang_prefix: "飘萍",
	qunfang_xiahoushi: "飘萍夏侯氏",
	qunfang_xiahoushi_prefix: "飘萍",
	qunfang_caiwenji: "飘萍蔡文姬",
	qunfang_caiwenji_prefix: "飘萍",
	qunfang_daqiao_xiaoqiao: "蒂莲大乔&小乔",
	qunfang_daqiao_xiaoqiao_prefix: "蒂莲",
	qunfang_wangtao_wangyue: "蒂莲王桃&王悦",
	qunfang_wangtao_wangyue_prefix: "蒂莲",
	qunfang_liuling_liupei: "蒂莲刘伶&刘佩",
	qunfang_liuling_liupei_prefix: "蒂莲",
	qunfang_lifuren: "烈蕙李夫人",
	qunfang_lifuren_prefix: "烈蕙",
	qunfang_zhaoe: "烈蕙赵娥",
	qunfang_zhaoe_prefix: "烈蕙",
	qunfang_xiahoulinnv: "烈蕙夏侯令女",
	qunfang_xiahoulinnv_prefix: "烈蕙",
	qunfang_dufuren: "芳葇杜夫人",
	qunfang_dufuren_prefix: "芳葇",
	qunfang_diaochan: "芳葇貂蝉",
	qunfang_diaochan_prefix: "芳葇",
};
